version: '3.3'

services:
  db:
    container_name: db
    build: ./db
    environment:
      - ACCEPT_EULA=y
      - sa_password=DockerOnW!nd0ws
    ports:
      - "1433" 
  web:
    container_name: web
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "80"
      - "8172"       
